version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_container
    ports:
      - "5000:5000"
    volumes:
      - ./Flask/project/myproject/instance:/app/myproject/instance  # Persist SQLite database
    environment:
      - FLASK_APP=/app/myproject/app.py
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
